workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - plan
  - apply
  - destroy

before_script:
  - cd ${CI_PROJECT_DIR}
  - terraform init -upgrade

plan:
  stage: plan
  script:
    - terraform fmt
    - terraform validate
    - terraform plan

apply:
  stage: apply
  script:
    - terraform apply -auto-approve
  allow_failure: true
  when: manual

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
