workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

default:
  image:
    name: alpine:latest
  before_script:
    - apk add terraform git python3 py3-pip openssh --no-cache
    - terraform init -upgrade -reconfigure -backend-config="password=${CI_JOB_TOKEN}"

stages:
  - plan
  - apply
  - ansible
  - destroy

plan:
  stage: plan
  before_script:
    - apk add terraform git --no-cache
    - cd ${CI_PROJECT_DIR}/terraform
    - terraform init -upgrade -reconfigure -backend-config="password=${CI_JOB_TOKEN}"
  script:
    - terraform fmt
    - terraform validate
    - terraform plan

apply:
  stage: apply
  before_script:
    - apk add terraform git --no-cache
    - cd ${CI_PROJECT_DIR}/terraform
    - terraform init -upgrade -reconfigure -backend-config="password=${CI_JOB_TOKEN}"
  script:
    - terraform apply -auto-approve
  allow_failure: true
  artifacts:
    paths:
      - terraform/tf_ansible_vars_file.yml
  when: manual

ansible:
  stage: ansible
  script:
    - apk add openssh ansible --no-cache
    - cd ${CI_PROJECT_DIR}/ansible
    - cat inventory.yaml
    - echo "$SSH_PRIVATE_KEY" > ssh_key_file
    - chmod 600 ssh_key_file
    - ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook -i inventory.yml main.yml --key-file ssh_key_file
  allow_failure: true
  when: manual

destroy:
  stage: destroy
  before_script:
    - apk add terraform git --no-cache
    - cd ${CI_PROJECT_DIR}/terraform
    - terraform init -upgrade -reconfigure -backend-config="password=${CI_JOB_TOKEN}"
  script:
    - terraform destroy -auto-approve
  when: manual
