workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "kpn_tf_ansible"

default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

stages:
  - plan
  - apply
  - ansible
  - destroy

# before_script:
#   - cd ${CI_PROJECT_DIR}/terraform
#   - terraform init -upgrade -reconfigure -backend-config="password=${CI_JOB_TOKEN}"

plan:
  stage: plan
  before_script:
    - cd ${CI_PROJECT_DIR}/terraform
    - terraform init -upgrade -reconfigure -backend-config="password=${CI_JOB_TOKEN}"
  script:
    - terraform fmt
    - terraform validate
    - terraform plan

apply:
  stage: apply
  before_script:
    - cd ${CI_PROJECT_DIR}/terraform
    - terraform init -upgrade -reconfigure -backend-config="password=${CI_JOB_TOKEN}"
  script:
    - terraform apply -auto-approve
  allow_failure: true
  when: manual

ansible:
  image: python:3.9.17-slim-bullseye
  stage: ansible
  script:
    - cd ${CI_PROJECT_DIR}/ansible
    - python -m ansible/inventory # generate inventory.yml
    # - ansible-playbook -i inventory ansible/main.yml # run ansible
    - |
      echo "$SSH_PRIVATE_KEY" > ssh_key_file
      chmod 600 ssh_key_file
      ssh-agent bash -c 'ssh-add ssh_key_file && ansible-playbook -i inventory ansible/main.yml'
  allow_failure: true
  when: manual

destroy:
  stage: destroy
  before_script:
    - cd ${CI_PROJECT_DIR}/terraform
    - terraform init -upgrade -reconfigure -backend-config="password=${CI_JOB_TOKEN}"
  script:
    - terraform destroy -auto-approve
  when: manual
