workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"


stages:
  - plan
  - apply
  - ansible
  - destroy

before_script:
  - cd ${CI_PROJECT_DIR}
  - terraform init -upgrade

plan:
  stage: plan
  script:
    - terraform fmt
    - terraform validate
    - terraform plan

apply:
  stage: apply
  script:
    - terraform apply -auto-approve
  allow_failure: true
  when: manual

ansible:
  stage: ansible
  script:
    - python3 -m ansible/inventory # generate inventory.yml
    - ansible-playbook -i inventory ansible/main.yml # run ansible
  allow_failure: true
  when: manual


destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
