workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

image:
  name: registry.code.fbi.h-da.de/cloud-computing-technology/lab/2023_ws/group_b_8_ci_base_image/base_image:latest

stages:
  - plan
  - apply
  - destroy

before_script:
  - cd ${CI_PROJECT_DIR}
  - terraform init -upgrade

plan:
  stage: plan
  script:
    - terraform fmt
    - terraform validate
    - terraform plan

apply:
  stage: apply
  script:
    - terraform apply -auto-approve
  allow_failure: true
  when: manual

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
