---
- name: Terraform Playbook
  hosts: all
  become: true

  tasks:
    - name: Install updates and upgrades
      apt:
        update_cache: yes
        upgrade: dist
        
    - name: Install nginx
      apt:
        name: nginx
        state: latest