- name: Install dependencies apt-transport-https
  ansible.builtin.apt:
    name:
      - apt-transport-https
    state: present
  # sudo apt-get install -y apt-transport-https

- name: Download Grafana package
  ansible.builtin.get_url:
    url: https://dl.grafana.com/oss/release/grafana_10.2.1_amd64.deb
    dest: /tmp/grafana_10.2.1_amd64.deb
    mode: '0644'
  # wget https://dl.grafana.com/oss/release/grafana_10.2.1_amd64.deb

- name: Install Grafana package
  ansible.builtin.apt:
    deb: /tmp/grafana_10.2.1_amd64.deb
  # dpkg -i grafana_10.2.1_amd64.deb

    # Config grafana dashboard

- name: Add grafana to bin PATH
  lineinfile:
    path: /tmp/script.sh  # Specify the path to your shell script on the remote server
    line: 'export PATH=$PATH:/usr/share/grafana/bin'
    create: yes
# export PATH=$PATH:/usr/share/grafana/bin

- name: Copy datasource.sh to remote server
  copy:
    src: ../grafanaScripts/datasource.sh  
    dest: /tmp  
- name: Make datasource.sh executable
  command: chmod +x /tmp/datasource.sh

- name: Copy import.sh to remote server
  copy:
    src: ../grafanaScripts/import.sh  
    dest: /tmp

- name: Make import.sh executable
  command: chmod +x /tmp/import.sh
