- name: Download Telegraf package
  ansible.builtin.get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.27.1-1_amd64.deb
    dest: /tmp/telegraf_1.27.1-1_amd64.deb
    mode: '0644'
  # wget https://dl.influxdata.com/telegraf/releases/telegraf_1.27.1-1_amd64.deb

- name: Install Telegraf package
  ansible.builtin.apt:
    deb: /tmp/telegraf_1.27.1-1_amd64.deb
  # dpkg -i telegraf_1.27.1-1_amd64.deb

# Configure telegraf
- name: Uncomment influxdb plugin
  ansible.builtin.replace:
    path: /etc/telegraf/telegraf.conf
    regexp: '.*(\[\[outputs\.influxdb\]\])'
    replace: '\1'

- name: Uncomment net plugin
  ansible.builtin.replace:
    path: /etc/telegraf/telegraf.conf
    regexp: '.*(\[\[inputs\.netstat\]\])'
    replace: '\1'

- name: Uncomment interfaces
  ansible.builtin.replace:
    path: /etc/telegraf/telegraf.conf
    after: '\[\[inputs\.net\]\]'
    regexp: '.*(interfaces = .*)'
    replace: '\1'

- name: Uncomment netstat plugin
  ansible.builtin.replace:
    path: /etc/telegraf/telegraf.conf
    regexp: '.*(\[\[inputs\.net\]\])'
    replace: '\1'

- name: Uncomment file descriptor plugin
  ansible.builtin.replace:
    path: /etc/telegraf/telegraf.conf
    regexp: '.*(\[\[inputs\.linux_sysctl_fs\]\])'
    replace: '\1'

- name: Uncomment procstat plugin
  ansible.builtin.replace:
    path: /etc/telegraf/telegraf.conf
    regexp: '.*(\[\[inputs\.procstat\]\])'
    replace: '\1'

- name: Uncomment pattern procstat
  ansible.builtin.replace:
    path: /etc/telegraf/telegraf.conf
    after: '\[\[inputs\.net\]\]'
    before: '\[\[inputs\.proxmox\]\]'
    regexp: '.*(pattern =).*'
    replace: '\1 "httpd|ansible|telegraf|nginx"'

- name: Uncomment user procstat
  ansible.builtin.replace:
    path: /etc/telegraf/telegraf.conf
    after: '\[\[inputs\.net\]\]'
    regexp: '.*(user =).*'
    replace: '\1 "daemon|root|telegraf"'

- name: Uncomment local url
  ansible.builtin.replace:
    path: /etc/telegraf/telegraf.conf
    after: '\[\[outputs\.influxdb\]\]'
    regexp: '.*(urls = \[\"http://)[0-9.]+(:8086\"\])'
    replace: '\g<1>{{ lookup("env", "TF_VAR_fixed_ip") }}\2'
