- name: Install dependencies apt-transport-https
  ansible.builtin.apt:
    name:
      - apt-transport-https
    state: present
  # sudo apt-get install -y apt-transport-https

- name: Download Grafana package
  ansible.builtin.get_url:
    url: https://dl.grafana.com/oss/release/grafana_10.2.1_amd64.deb
    dest: /tmp/grafana_10.2.1_amd64.deb
    mode: '0644'
  # wget https://dl.grafana.com/oss/release/grafana_10.2.1_amd64.deb

- name: Install Grafana package
  ansible.builtin.apt:
    deb: /tmp/grafana_10.2.1_amd64.deb
  # dpkg -i grafana_10.2.1_amd64.deb
