- name: Install needed packages
  hosts: host
  become: true
  vars:
    packages_dir: "packages_playbooks"

  tasks:
    - name: Update apt repositories
      ansible.builtin.apt:
        update_cache: true

    - name: Install dependency jq # needed for execute import script
      ansible.builtin.apt:
        name:
        - jq
        state: present
        # sudo apt-get install -y jq

# Install nginx
    - name: Install nginx
      ansible.builtin.import_tasks: "{{ packages_dir }}/nginx.yaml"

# Install and Configure telegraf
    - name: Install and configure telegraf
      ansible.builtin.import_tasks: "{{ packages_dir }}/telegraf.yaml"

# Install and Configure influxdb
    - name: Install and configure influxdb
      ansible.builtin.import_tasks: "{{ packages_dir }}/influxdb.yaml"

# Install and Configure grafana
    - name: Install and configure grafana
      ansible.builtin.import_tasks: "{{ packages_dir }}/grafana.yaml"

# Start services
    - name: Start and enable Telegraf service
      ansible.builtin.systemd:
        name: telegraf
        state: started
        enabled: true
      # sudo systemctl enable telegraf --now

    - name: Start and enable Grafana service
      ansible.builtin.systemd:
        name: grafana-server
        state: started
        enabled: true
      # sudo systemctl enable grafana --now

    - name: Sleep command to wait grafana to start
      command: sleep 10  # Adjust the time

    - name: Execute the datasource shell script
      shell: /tmp/datasource.sh
      register: datasource_script_output
   #  ./datasource.sh

    - name: Display the grafana datasource script output
      ansible.builtin.debug:
        var: datasource_script_output.stdout_lines

    - name: Execute the import shell script
      shell: /tmp/import.sh
      register: import_script_output
   #  ./datasource.sh

    - name: Display the grafana import script output
      ansible.builtin.debug:
        var: import_script_output.stdout_lines
